update script

diff --git a/.github/actions/buildcook/action.yml b/.github/actions/buildcook/action.yml
--- a/.github/actions/buildcook/action.yml
+++ b/.github/actions/buildcook/action.yml
@@ -42,7 +42,7 @@ runs:
   steps:
     - name: Build cook and package unreal project
       shell: bash
-      
+
       env: 
         m_runUatPath: "/home/ubuntu/UE/Linux_Unreal_Engine_5.4.1/Engine/Build/BatchFiles/RunUAT.sh"
         m_buildConfig: ${{ inputs.build_config }} #"Development"
@@ -52,15 +52,19 @@ runs:
         m_archivePath: ${{ inputs.archive_path }}
         m_maps: ${{ inputs.maps }} #"false"
       run: |
+        echo 'Project path on runner is: '${{ github.workspace }}
+
         if [ "${m_archivePath:-1}"!="/"];then
           m_archivePath="${{ inputs.archive_path }}/"
         fi
 
+        echo 'Package archive path is: '${{ env.m_archivePath }}
+
         # Make sure there is only one uproject file in the project.
         uprojectCount=$(find .. -type f -name "*.uproject" | wc -l) 
         if [ "$uprojectCount" != 1 ]; then
-          echo "Error: $uprojectCount uproejct files exist.Please make sure there is only one uproject file in the project!"
-          exit 1
+          echo "::error::$uprojectCount uproejct files exist.Please make sure there is only one uproject file in the project!"
+          exit 3
         fi
 
         # Search for *.uproject file in the upper folder and change the relative path into absolute
