update script

diff --git a/.github/workflows/app.yml b/.github/workflows/app.yml
--- a/.github/workflows/app.yml
+++ b/.github/workflows/app.yml
@@ -77,7 +77,7 @@ jobs:
     needs: clean-workspace
     outputs: 
       dispatch_release: ${{ steps.check-if-release-dispatch.outputs.publish_release }}
-      push_release: ${{ steps.check-if-release-push.outputs.push_release }}
+      push_release: ${{ steps.check-if-release-push.outputs.publish_release }}
 
     steps:
       - name: Checkout project
@@ -101,13 +101,18 @@ jobs:
       - name: Check if publish release
         id: check-if-release-dispatch
         run: |
-          echo "publish_release=true" >> $GITHUB_OUTPUT
-          echo 'Build: App version starts with v, it will publish to release'
+          if [ ${{ startsWith(env.app_version, 'v') }}]; then
+            echo "publish_release=true" >> $GITHUB_OUTPUT
+            echo 'Build: App version starts with v, it will publish to release'
+          else
+            echo "publish_release=false" >> $GITHUB_OUTPUT
+          fi
 
       - name: Check if publish release on push
         id: check-if-release-push
         if: ${{ startsWith(github.ref, 'refs/tags') }}
         run: |
+          # TODO: check the push tag starts with v
           echo "publish_release=true" >> $GITHUB_OUTPUT
           echo 'Build: Pushed tag starts with v, it will publish to release'
 
@@ -149,14 +154,16 @@ jobs:
 
       - name: Check tag availability
         id: check-tag
-        if: ${{ startsWith(env.app_version, 'v') && contains(steps.get-tags.outputs.result, env.app_version) }}
         run: |
-          echo '::error::Error: Version ${{ env.app_version }} already exists, please reset it with a new one'
+          if [ contains(steps.get-tags.outputs.result, env.app_version) ]; then
+            echo '::error::Error: Version ${{ env.app_version }} already exists, please reset it with a new one'
+            exit 1
+          fi
               
       - name: Create tag
         id: create-tag
         if: 
-          ${{ startsWith(env.app_version, 'v') && !contains(steps.get-tags.outputs.result, env.app_version)}}
+          ${{ env.tag }}
         uses: actions/github-script@v7
         with:
           script: |
