test

diff --git a/.github/workflows/app.yml b/.github/workflows/app.yml
--- a/.github/workflows/app.yml
+++ b/.github/workflows/app.yml
@@ -238,7 +238,8 @@ jobs:
               \"draft\": false,
               \"prerelease\": false
             }")
-          echo "::error:: testing, delete this when commit"
+          echo "::error:: test message!"
+          exit 9
           echo "Create release: response is:\n$response"
       
       - name: Clean s3 bucket
